// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0UZeKXBy1YN4On7ETYrilbgb93nxiJw4',
    appId: '1:469604483366:web:3c846c37277323573881e7',
    messagingSenderId: '469604483366',
    projectId: 'fir-flutter-codelab2-f5827',
    authDomain: 'fir-flutter-codelab2-f5827.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab2-f5827.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQsahqtyLnsb3g1GtPUDT7K5ZFh7DWvNI',
    appId: '1:469604483366:android:ceadfbe97a6487853881e7',
    messagingSenderId: '469604483366',
    projectId: 'fir-flutter-codelab2-f5827',
    storageBucket: 'fir-flutter-codelab2-f5827.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs6Ylqf86ZC4V2rAtfQ1GnKdtNSdvu0KU',
    appId: '1:469604483366:ios:9a57959064e2d7a13881e7',
    messagingSenderId: '469604483366',
    projectId: 'fir-flutter-codelab2-f5827',
    storageBucket: 'fir-flutter-codelab2-f5827.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs6Ylqf86ZC4V2rAtfQ1GnKdtNSdvu0KU',
    appId: '1:469604483366:ios:9a57959064e2d7a13881e7',
    messagingSenderId: '469604483366',
    projectId: 'fir-flutter-codelab2-f5827',
    storageBucket: 'fir-flutter-codelab2-f5827.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
