name: quiz
description: A quiz app for demonstrating animation effects in Flutter
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  animations: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
