name: generate_crossword
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-0

dependencies:
  flutter:
    sdk: flutter
  built_collection: ^5.1.1
  built_value: ^8.9.2
  characters: ^1.3.0
  flutter_riverpod: ^2.5.3
  intl: ^0.19.0
  riverpod: ^2.5.3
  riverpod_annotation: ^2.5.3
  two_dimensional_scrollables: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  built_value_generator: ^8.9.2
  custom_lint: ^0.6.10
  riverpod_generator: ^2.4.4
  riverpod_lint: ^2.3.14

flutter:
  uses-material-design: true
  assets:
    - assets/words.txt
