dict_value {
  fields {
    key: "collect_data_spec"
    value {
      named_tuple_value {
        name: "Trajectory"
        values {
          key: "step_type"
          value {
            tensor_spec_value {
              name: "step_type"
              shape {
              }
              dtype: DT_INT32
            }
          }
        }
        values {
          key: "observation"
          value {
            bounded_tensor_spec_value {
              shape {
                dim {
                  size: 8
                }
                dim {
                  size: 8
                }
              }
              dtype: DT_FLOAT
              minimum {
                dtype: DT_FLOAT
                tensor_shape {
                }
                float_val: -1.0
              }
              maximum {
                dtype: DT_FLOAT
                tensor_shape {
                }
                float_val: 1.0
              }
            }
          }
        }
        values {
          key: "action"
          value {
            bounded_tensor_spec_value {
              shape {
              }
              dtype: DT_INT32
              minimum {
                dtype: DT_INT32
                tensor_shape {
                }
                int_val: 0
              }
              maximum {
                dtype: DT_INT32
                tensor_shape {
                }
                int_val: 63
              }
            }
          }
        }
        values {
          key: "policy_info"
          value {
            tuple_value {
            }
          }
        }
        values {
          key: "next_step_type"
          value {
            tensor_spec_value {
              name: "step_type"
              shape {
              }
              dtype: DT_INT32
            }
          }
        }
        values {
          key: "reward"
          value {
            tensor_spec_value {
              name: "reward"
              shape {
              }
              dtype: DT_FLOAT
            }
          }
        }
        values {
          key: "discount"
          value {
            bounded_tensor_spec_value {
              name: "discount"
              shape {
              }
              dtype: DT_FLOAT
              minimum {
                dtype: DT_FLOAT
                tensor_shape {
                }
                float_val: 0.0
              }
              maximum {
                dtype: DT_FLOAT
                tensor_shape {
                }
                float_val: 1.0
              }
            }
          }
        }
      }
    }
  }
  fields {
    key: "policy_state_spec"
    value {
      tuple_value {
      }
    }
  }
}
