name: firebase_auth_flutterfire_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  firebase_ui_auth: ^3.0.1
  firebase_ui_oauth_google: ^2.0.1
  flutter:
    sdk: flutter
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
