// Copyright 2022 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  // TODO: remove keys when finished
  // although you are encouraged to leave Firebase keys in projects, as they are _not_ secrets,
  // I want readers to set up their own Firebase project.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD3sv4BvbPJiNgwalcmOKMAT18cVaMM9E',
    appId: '1:205432643314:web:883ee969975ceb42043a6b',
    messagingSenderId: '205432643314',
    projectId: 'flutterfire-abtest-codelab',
    authDomain: 'flutterfire-abtest-codelab.firebaseapp.com',
    storageBucket: 'flutterfire-abtest-codelab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe1yEiwa71_dHHyCz2RbBNyKXhsdewkiQ',
    appId: '1:205432643314:android:73cf1d5d8af78732043a6b',
    messagingSenderId: '205432643314',
    projectId: 'flutterfire-abtest-codelab',
    storageBucket: 'flutterfire-abtest-codelab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGT30CKB2HjlJb12R55jW3z7P_EcLK7MY',
    appId: '1:205432643314:ios:685838d6764e685d043a6b',
    messagingSenderId: '205432643314',
    projectId: 'flutterfire-abtest-codelab',
    storageBucket: 'flutterfire-abtest-codelab.appspot.com',
    iosClientId:
        '205432643314-inpi030psqis8i267su6a9gjtf985h4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGT30CKB2HjlJb12R55jW3z7P_EcLK7MY',
    appId: '1:205432643314:ios:685838d6764e685d043a6b',
    messagingSenderId: '205432643314',
    projectId: 'flutterfire-abtest-codelab',
    storageBucket: 'flutterfire-abtest-codelab.appspot.com',
    iosClientId:
        '205432643314-inpi030psqis8i267su6a9gjtf985h4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );
}
