// File normally generated by FlutterFire CLI. This is a stand-in.
// Remove this file and run `flutterfire configure`
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  // TODO: Run `flutterfire configure` to re-generate this file
  static FirebaseOptions get currentPlatform {
    throw UnimplementedError(
      'Regenerate this file by running `flutterfire configure`. ',
    );
  }
}
