name: Gerar APK Flutter

on:
  push:
      branches: [ main, master ]
        workflow_dispatch: # Permite criar o APK clicando em um botão no site do GitHub

        jobs:
          build:
              runs-on: ubuntu-latest

                  steps:
                      - uses: actions/checkout@v4

                          - name: Configurar Java
                                uses: actions/setup-java@v4
                                      with:
                                              distribution: 'zulu'
                                                      java-version: '17'

                                                          - name: Configurar Flutter
                                                                uses: subosito/flutter-action@v2
                                                                      with:
                                                                              channel: 'stable'

                                                                                  - name: Obter dependências
                                                                                        run: |
                                                                                                cd app_novo
                                                                                                        flutter pub get

                                                                                                            - name: Gerar APK
                                                                                                                  run: |
                                                                                                                          cd app_novo
                                                                                                                                  flutter build apk --release

                                                                                                                                      - name: Enviar APK para Download
                                                                                                                                            uses: actions/upload-artifact@v4
                                                                                                                                                  with:
                                                                                                                                                          name: meu-app-release
                                                                                                                                                                  path: app_novo/build/app/outputs/flutter-apk/app-release.apk