name: Gerar APK Flutter
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Build
      run: |
        cd app_novo
        flutter pub get
        flutter build apk --release
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: meu-app-novo-pronto
        path: app_novo/build/app/outputs/flutter-apk/app-release.apk
