name: firebase_backend_dart
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

dependencies:
  app_store_server_sdk: ^1.2.10
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.5.0
  shelf: ^1.4.2
  shelf_router: ^1.1.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
